baseURL = "https://www.blokje5.dev"
title = "blokje5.dev"
theme = "hugo-coder"
locale = "en"
defaultContentLanguage = "en"

[markup]
  [markup.highlight]
    style = "github-dark"
    guessSyntax = true
  [markup.goldmark.renderer]
    unsafe = true

[params]
  author = "Lennard Eijsackers"
  info = "Data Engineer"
  description = "Lennard Eijsackers developer blog"
  keywords = "blog,developer,personal"
  dateFormat = "January 2, 2006"
  colorScheme = "auto"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

[params.giscus]
  repo = "Blokje5/blokje5.dev"
  repoID = "MDEwOlJlcG9zaXRvcnkxOTUyOTA2NDE="
  category = "Announcements"
  categoryID = "DIC_kwDOC6PmEc4DBP-j"
  theme = "preferred_color_scheme"
  mapping = "pathname"
  reactionsEnabled = "1"
  inputPosition = "top"
  lang = "en"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/Blokje5/"
[[params.social]]
  name = "X"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/LennardNL/"
[[params.social]]
  name = "Stackoverflow"
  icon = "fa-brands fa-stack-overflow fa-2x"
  weight = 3
  url = "https://stackoverflow.com/users/9741769/blokje5/"
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 4
  url = "https://www.linkedin.com/in/lennard-eijsackers/"
