[build]
publish = "public"
command = "hugo --gc --minify --baseURL $URL"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture --baseURL $DEPLOY_URL"

[context.branch-deploy]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"